Repository MoyeoRun/MoyeoRun_Front, pull requests merged in 2021-11, with the labels that each got.

#27 JWT 관리 구현
  package.json
  src/App.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/HomeTab/LastRecord.tsx
  src/components/HomeTab/NewMission.tsx
  src/components/Login/GetCodeView.tsx
  src/components/Login/Login.tsx
  src/containers/HomeTabContainer.tsx
  src/containers/LoginContainer.tsx
  src/hooks/TokenProvider.tsx
  src/hooks/useCachedResources.ts
  src/lib/api/auth.ts
  src/lib/api/user.ts
  src/middlewares/actionMiddleware.ts
  src/modules/auth.ts
  src/modules/index.ts
  src/modules/user.ts
  src/navigation/index.tsx
  src/store.ts
  yarn.lock
Labels: Feature ✨

#28 Feat: BodyInfo 등록 기능 구현
  .prettierrc
  .vscode/containerSnippet.code-snippets
  src/App.tsx
  src/components/BodyInfo/BodyInfo.tsx
  src/components/BodyInfo/BodyInfoPicker.tsx
  src/components/MyPage/MyPage.tsx
  src/containers/BodyInfoContainer.tsx
  src/containers/LoginContainer.tsx
  src/containers/MyPageContainer.tsx
  src/hooks/TokenProvider.tsx
  src/hooks/customTheme.ts
  src/lib/api/auth.ts
  src/lib/api/user.ts
  src/modules/user.ts
  src/navigation/index.tsx
Labels: Feature ✨

#29 Feature/single
  package.json
  src/assets/svg/BackIcon.tsx
  src/assets/svg/CheckIcon.tsx
  src/assets/svg/PauseIcon.tsx
  src/assets/svg/PlayIcon.tsx
  src/assets/svg/StopIcon.tsx
  src/assets/svg/ToggleArrowIcon.tsx
  src/components/RunningTab/SingleFreeRunning.tsx
  src/components/SingleFreeRun/Map.tsx
  src/components/SingleFreeRun/ModeSelect.tsx
  src/components/SingleFreeRun/OnSingleRunning.tsx
  src/components/SingleFreeRun/OperationButton.tsx
  src/components/SingleFreeRun/Pagination.tsx
  src/components/SingleFreeRun/SingleFreeRun.tsx
  src/components/SingleFreeRun/ValuePicker.tsx
  src/components/SingleFreeRun/WithMap.tsx
  src/components/SingleFreeRun/WithPace.tsx
  src/components/SingleFreeRun/index.ts
  src/navigation/LinkingConfiguration.ts
  src/navigation/index.tsx
  src/types.tsx
  yarn.lock
Labels: Feature ✨

#30 Hotfix : bottom tab 아이콘 디테일 수정
  src/assets/svg/FocusedMissionIcon.tsx
  src/assets/svg/FriendIcon.tsx
  src/assets/svg/HomeIcon.tsx
  src/assets/svg/MissionIcon.tsx
  src/assets/svg/RecordIcon.tsx
  src/assets/svg/RunningIcon.tsx
  src/assets/svg/index.ts
  src/navigation/index.tsx
Labels: Fixed 🔧

#32 Feature/room
  package.json
  src/assets/svg/NumberInputIcon.tsx
  src/assets/svg/index.ts
  src/components/MoyeoRunRoom/MoyeoRunRoom.tsx
  src/components/MoyeoRunRoom/NumberInputPicker.tsx
  src/components/MoyeoRunRoom/SubmitButton.tsx
  src/components/MoyeoRunRoom/index.ts
  src/components/RunningTab/MakeRoomButton.tsx
  src/components/RunningTab/RunningTab.tsx
  src/components/common/CustomPicker.tsx
  src/navigation/LinkingConfiguration.ts
  src/navigation/index.tsx
  src/types.tsx
  yarn.lock
Labels: Feature ✨

#34 Refactor 파일명 / 구조 변경
  .vscode/moyeoRunComponent.code-snippets
  app.json
  package.json
  src/components/BodyInfo/BodyInfoPicker.tsx
  src/components/Card/RunCard.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/Login/GetCodeView.tsx
  src/components/RunningTab/MultiRunMain.tsx
  src/components/RunningTab/SingleFreeRunning.tsx
  src/components/RunningTab/SingleRunningGuide.tsx
  src/components/SingleFreeRun/Map.tsx
  src/components/SingleFreeRun/Pagination.tsx
  src/components/SingleFreeRun/index.ts
  src/components/SingleRun/Map.tsx
  src/components/SingleRun/ModeSelect.tsx
  src/components/SingleRun/OperationButton.tsx
  src/components/SingleRun/ReadySingleRun.tsx
  src/components/SingleRun/SingleRunMap.tsx
  src/components/SingleRun/SingleRunPace.tsx
  src/components/SingleRun/SingleRunning.tsx
  src/components/SingleRun/ValuePicker.tsx
  src/components/SingleRun/index.ts
  src/containers/SingleRunMapContainer.tsx
  src/containers/SingleRunPaceContainer.tsx
  src/lib/api/run.ts
  src/lib/util/useInterval.ts
  src/middlewares/actionMiddleware.ts
  src/modules/auth.ts
  src/modules/index.ts
  src/modules/singleRun.ts
  src/modules/user.ts
  src/navigation/LinkingConfiguration.ts
  src/navigation/index.tsx
  src/types.tsx
  yarn.lock
Labels: Refactoring 🚜

#35 Feat: 개인런 기능 구현
  .gitignore
  package.json
  src/components/HomeTab/HomeTab.tsx
  src/components/SingleRun/Map.tsx
  src/components/SingleRun/OperationButton.tsx
  src/components/SingleRun/ReadySingleRun.tsx
  src/components/SingleRun/SingleRunMap.tsx
  src/components/SingleRun/SingleRunPace.tsx
  src/containers/SingleRunMapContainer.tsx
  src/hooks/TokenProvider.tsx
  src/hooks/useCachedResources.ts
  src/lib/api/auth.ts
  src/lib/api/run.ts
  src/lib/util/calcRunData.ts
  src/lib/util/strFormat.ts
  src/lib/util/useInterval.ts
  src/modules/singleRun.ts
  src/navigation/LinkingConfiguration.ts
  src/navigation/index.tsx
  src/types.tsx
  yarn.lock
Labels: Feature ✨

#44 Feat: #42 #43
  src/App.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/RunningTab/RunningTab.tsx
  src/components/common/CustomWebview.tsx
  src/containers/HomeTabContainer.tsx
  src/modules/auth.ts
  src/navigation/index.tsx
Labels: Feature ✨

#45 FIx: 다크모드 제거
  src/navigation/index.tsx
Labels: Fixed 🔧

#48 Feat: 개인런 기능 완료
  .vscode/moyeoRunWebview.code-snippets
  a.json
  package.json
  src/components/BottomTab/HomeTab.tsx
  src/components/BottomTab/RunningTab.tsx
  src/components/FriendTab/FriendTab.tsx
  src/components/HomeTab/FavoritRunning.tsx
  src/components/HomeTab/HomeTab.tsx
  src/components/HomeTab/LastRecord.tsx
  src/components/HomeTab/NewMission.tsx
  src/components/HomeTab/index.ts
  src/components/MissionTab/MissionTab.tsx
  src/components/NotFound.tsx
  src/components/RecordTab/RecordTab.tsx
  src/components/RunningTab/MakeRoomButton.tsx
  src/components/RunningTab/MultiRunMain.tsx
  src/components/RunningTab/RunModeStatus.tsx
  src/components/RunningTab/RunningTab.tsx
  src/components/RunningTab/SingleFreeRunning.tsx
  src/components/RunningTab/SingleRunMain.tsx
  src/components/RunningTab/SingleRunningGuide.tsx
  src/components/RunningTab/index.ts
  src/components/SingleRun/Map.tsx
  src/components/SingleRun/ReadySingleRun.tsx
  src/components/SingleRun/SingleRunMap.tsx
  src/components/SingleRun/SingleRunPace.tsx
  src/components/common/CustomWebview.tsx
  src/containers/HomeTabContainer.tsx
  src/containers/RunningTabContainer.tsx
  src/containers/SingleRunMapContainer.tsx
  src/lib/api/run.ts
  src/lib/util/strFormat.ts
  src/modules/singleRun.ts
  src/navigation/index.tsx
  yarn.lock
Labels: Feature ✨

#50 Refactor: 개인런 관련 최적화
  src/App.tsx
  src/components/SingleRun/OperationButton.tsx
  src/containers/SingleRunMapContainer.tsx
  src/lib/api/run.ts
  src/lib/util/useLongPress.ts
  src/navigation/index.tsx
Labels: Refactoring 🚜

#59 Refactor: 바텀 탭 아이콘 추가 및 svg 정리
  .expo-shared/assets.json
  .gitignore
  App.tsx
  a.json
  app.json
  package.json
  public/adaptive-icon.png
  public/favicon.png
  public/icon.png
  public/splash.png
  src/Notification.tsx
  src/assets/svg/FocusedMissionIcon.tsx
  src/assets/svg/FriendFillIcon.tsx
  src/assets/svg/FriendIcon.tsx
  src/assets/svg/HomeFillIcon.tsx
  src/assets/svg/MissionFillIcon.tsx
  src/assets/svg/MissionIcon.tsx
  src/assets/svg/RecordFillIcon.tsx
  src/assets/svg/RecordIcon.tsx
  src/assets/svg/RunningFillIcon.tsx
  src/assets/svg/RunningIcon.tsx
  src/assets/svg/index.ts
  src/components/BottomTab/HomeTab.tsx
  src/components/Login/GetCodeView.tsx
  src/components/Login/Login.tsx
  src/containers/SingleRunMapContainer.tsx
  src/lib/api/record.ts
  src/lib/api/room.ts
  src/lib/api/run.ts
  src/modules/auth.ts
  src/modules/multiRun.ts
  src/modules/room.ts
  src/modules/singleRun.ts
  src/modules/user.ts
  src/navigation/index.tsx
  src/navigationTypes.ts
  src/types.ts
  yarn.lock
Labels: Refactoring 🚜

#65 Feat API 연동
  .vscode/moyeoRunWebview.code-snippets
  package.json
  src/components/BottomTab/HomeTab.tsx
  src/components/SingleRun/ReadySingleRun.tsx
  src/components/SingleRun/SingleRunning.tsx
  src/components/UploadProfile.tsx
  src/components/Welcome.tsx
  src/components/auth/Login.tsx
  src/components/common/CustomWebview.tsx
  src/components/profile/MyPage.tsx
  src/components/profile/UploadProfile.tsx
  src/containers/UploadProfileContainer.tsx
  src/containers/auth/LoginContainer.tsx
  src/containers/bottomTab/HomeTabContainer.tsx
  src/containers/profile/MyPageContainer.tsx
  src/containers/profile/UploadProfileContainer.tsx
  src/lib/api/auth.ts
  src/lib/api/image.ts
  src/lib/api/notification.ts
  src/lib/api/record.ts
  src/lib/api/room.ts
  src/lib/api/run.ts
  src/lib/api/user.ts
  src/lib/hooks/useNotification.ts
  src/lib/util/validate.ts
  src/modules/auth.ts
  src/modules/image.ts
  src/modules/index.ts
  src/modules/multiRun.ts
  src/modules/record.ts
  src/modules/user.ts
  src/navigation/index.tsx
  src/types.ts
Labels: Feature ✨

#71 Feat 방 리스트, 생성 참여 기능 구현
  App.tsx
  src/assets/svg/FriendFillIcon.tsx
  src/assets/svg/HomeFillIcon.tsx
  src/components/BottomTab/RecordTab.tsx
  src/components/BottomTab/RunningTab.tsx
  src/components/SingleRun/ReadySingleRun.tsx
  src/components/SingleRun/SingleRunning.tsx
  src/components/auth/Login.tsx
  src/components/multiRun/CreateMultiRoom.tsx
  src/components/multiRun/MultiRoom.tsx
  src/containers/auth/LoginContainer.tsx
  src/containers/bottomTab/FriendTabContainer.tsx
  src/containers/bottomTab/HomeTabContainer.tsx
  src/containers/bottomTab/MissionTabContainer.tsx
  src/containers/bottomTab/RecordTabContainer.tsx
  src/containers/bottomTab/RunningTabContainer.tsx
  src/containers/multiRun/CreateMultiRoomContainer.tsx
  src/containers/multiRun/MultiRoomContainer.tsx
  src/containers/profile/MyPageContainer.tsx
  src/containers/profile/UploadProfileContainer.tsx
  src/lib/api/room.ts
  src/lib/styles/colors.ts
  src/modules/room.ts
  src/navigation/index.tsx
  src/navigationTypes.ts
  src/types.ts
Labels: Feature ✨

#72 Feat: 소켓 연결 및 redux 상태 관리
  App.tsx
  package.json
  src/containers/bottomTab/HomeTabContainer.tsx
  src/lib/hooks/useSocket.ts
  src/modules/index.ts
  src/modules/socket.ts
  yarn.lock
Labels: Feature ✨

#81 Refactor: 모여런 기능 안정화
  src/components/BottomTab/RecordTab.tsx
  src/components/multiRun/MultiRun.tsx
  src/containers/bottomTab/RecordTabContainer.tsx
  src/containers/bottomTab/RunningTabContainer.tsx
  src/containers/multiRun/MultiRoomContainer.tsx
  src/containers/multiRun/MultiRunContainer.tsx
  src/lib/api/run.ts
  src/modules/multiRun.ts
  src/service/SocketProvider.tsx
Labels: Refactoring 🚜

#82 Feat 공유 기능 추가
  package.json
  src/assets/svg/LogoMini.tsx
  src/components/BottomTab/HomeTab.tsx
  src/components/ShareRunData.tsx
  src/components/record/SIngleRecordDetail.tsx
  yarn.lock
Labels: Feature ✨
